on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: cd Api && dotnet publish -c Release -o publish
      - uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          appdir: "Api"
        env: #only the key names below should be prefixed HD_ and the ${{secrets.NAME}} should not
          HD_AZ_VISION: ${{secrets.AZ_VISION}}
          HD_AZ_CONTENT_FILTER: ${{secrets.AZ_CONTENT_FILTER}}
          HD_JWT_KEY: ${{secrets.JWT_KEY}}
          HD_PG_CONN: ${{secrets.PG_CONN}}