on:
  workflow_dispatch:
  push:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: cd Tests && dotnet test
        env:
            HD_AZ_VISION: ${{secrets.AZ_VISION}}
            HD_AZ_CONTENT_FILTER: ${{secrets.AZ_CONTENT_FILTER}}
            HD_JWT_KEY: ${{secrets.JWT_KEY_}}
            HD_PG_CONN: ${{secrets.PG_CONN}}